#!/bin/bash

# Atlas AI - Render.com Deployment Guide
# Render requires GitHub, so this is a manual setup guide

echo "🚀 Atlas AI - Render.com Deployment"
echo "===================================="
echo ""
echo "⚠️  Render.com requires deploying from a Git repository."
echo ""
echo "📝 Step-by-step instructions:"
echo ""
echo "1. Push your code to GitHub:"
echo "   git init"
echo "   git add ."
echo "   git commit -m 'Initial commit for Atlas AI'"
echo "   git remote add origin YOUR_GITHUB_REPO_URL"
echo "   git push -u origin main"
echo ""
echo "2. Go to https://render.com and sign up (FREE, no credit card)"
echo ""
echo "3. Click 'New +' → 'Web Service'"
echo ""
echo "4. Connect your GitHub repository"
echo ""
echo "5. Configure the service:"
echo "   - Name: atlas-ai-backend"
echo "   - Region: Oregon (US West)"
echo "   - Root Directory: backend"
echo "   - Environment: Docker"
echo "   - Plan: Free"
echo ""
echo "6. Add Environment Variables:"
echo "   - DB_NAME: atlas_ai_db"
echo "   - CORS_ORIGINS: *"
echo "   - MONGO_URL: (your MongoDB Atlas URL)"
echo ""
echo "7. Add a Disk:"
echo "   - Name: chroma-data"
echo "   - Mount Path: /app/chroma_db"
echo "   - Size: 1GB"
echo ""
echo "8. Click 'Create Web Service'"
echo ""
echo "9. Wait 5-10 minutes for deployment"
echo ""
echo "10. Your backend URL will be: https://atlas-ai-backend.onrender.com"
echo ""
echo "📌 IMPORTANT: Free tier spins down after 15 minutes!"
echo "   Solution: Use UptimeRobot to keep it awake (see below)"
echo ""
echo "🔄 Keep-Alive Setup (Prevents Spin-Down):"
echo ""
echo "1. Go to https://uptimerobot.com (FREE, no credit card)"
echo ""
echo "2. Sign up and create new monitor:"
echo "   - Monitor Type: HTTP(s)"
echo "   - Friendly Name: Atlas AI Backend"
echo "   - URL: https://atlas-ai-backend.onrender.com/api/"
echo "   - Monitoring Interval: 5 minutes"
echo ""
echo "3. Click 'Create Monitor'"
echo ""
echo "✅ Done! Your backend will stay awake."
echo ""
echo "📝 Next steps:"
echo "   1. Update extension/config.js with your Render URL"
echo "   2. Load extension in Chrome"
echo "   3. Configure your LLM API key"
echo ""

